/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ctci;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    
    @Test 
    public void appHasAGreeting() {
        App classUnderTest = new App();
        System.out.println("Hello World!!");
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
